package cn.sz.gl.pojo;

// Generated 2017-3-1 10:46:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", catalog = "taiding")
public class Menu implements java.io.Serializable {

	private Integer menuid;
	private String menuName;
	private Integer parentid;
	private String menuPath;
	private String menuDesc;
	private String menuStatus;
	private String menuFocus;
	private Set<Succase> succases = new HashSet<Succase>(0);
	private Set<News> newses = new HashSet<News>(0);

	public Menu() {
	}

	public Menu(String menuName) {
		this.menuName = menuName;
	}

	public Menu(String menuName, Integer parentid, String menuPath,
			String menuDesc, String menuStatus, String menuFocus, Set<Succase> succases,
			Set<News> newses) {
		this.menuName = menuName;
		this.parentid = parentid;
		this.menuPath = menuPath;
		this.menuDesc = menuDesc;
		this.menuStatus = menuStatus;
		this.menuFocus = menuFocus;
		this.succases = succases;
		this.newses = newses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "menuid", unique = true, nullable = false)
	public Integer getMenuid() {
		return this.menuid;
	}

	public void setMenuid(Integer menuid) {
		this.menuid = menuid;
	}

	@Column(name = "menu_name", nullable = false, length = 50)
	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	@Column(name = "parentid")
	public Integer getParentid() {
		return this.parentid;
	}

	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	@Column(name = "menu_path", length = 100)
	public String getMenuPath() {
		return this.menuPath;
	}

	public void setMenuPath(String menuPath) {
		this.menuPath = menuPath;
	}

	@Column(name = "menu_desc")
	public String getMenuDesc() {
		return this.menuDesc;
	}

	public void setMenuDesc(String menuDesc) {
		this.menuDesc = menuDesc;
	}

	@Column(name = "menu_status", length = 10)
	public String getMenuStatus() {
		return this.menuStatus;
	}

	public void setMenuStatus(String menuStatus) {
		this.menuStatus = menuStatus;
	}

	@Column(name = "menu_focus", length = 10)
	public String getMenuFocus() {
		return this.menuFocus;
	}

	public void setMenuFocus(String menuFocus) {
		this.menuFocus = menuFocus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
	public Set<Succase> getSuccases() {
		return this.succases;
	}

	public void setSuccases(Set<Succase> succases) {
		this.succases = succases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
	public Set<News> getNewses() {
		return this.newses;
	}

	public void setNewses(Set<News> newses) {
		this.newses = newses;
	}

}
