package cn.sz.gl.pojo;

// Generated 2017-3-1 10:46:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * News generated by hbm2java
 */
@Entity
@Table(name = "news", catalog = "taiding")
public class News implements java.io.Serializable {

	private Integer newid;
	private Menu menu;
	private String title;
	private String picpath;
	private Date publicTime;
	private String newUrl;
	private String newDesc;
	private Integer newClickCount;
	private String newStatus;

	public News() {
	}

	public News(String title) {
		this.title = title;
	}

	public News(Menu menu, String title, String picpath, Date publicTime,
			String newUrl, String newDesc, Integer newClickCount,
			String newStatus) {
		this.menu = menu;
		this.title = title;
		this.picpath = picpath;
		this.publicTime = publicTime;
		this.newUrl = newUrl;
		this.newDesc = newDesc;
		this.newClickCount = newClickCount;
		this.newStatus = newStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "newid", unique = true, nullable = false)
	public Integer getNewid() {
		return this.newid;
	}

	public void setNewid(Integer newid) {
		this.newid = newid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "new_style")
	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	@Column(name = "title", nullable = false, length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "picpath", length = 100)
	public String getPicpath() {
		return this.picpath;
	}

	public void setPicpath(String picpath) {
		this.picpath = picpath;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "public_time", length = 0)
	public Date getPublicTime() {
		return this.publicTime;
	}

	public void setPublicTime(Date publicTime) {
		this.publicTime = publicTime;
	}

	@Column(name = "new_url", length = 100)
	public String getNewUrl() {
		return this.newUrl;
	}

	public void setNewUrl(String newUrl) {
		this.newUrl = newUrl;
	}

	@Column(name = "new_desc", length = 500)
	public String getNewDesc() {
		return this.newDesc;
	}

	public void setNewDesc(String newDesc) {
		this.newDesc = newDesc;
	}

	@Column(name = "new_click_count")
	public Integer getNewClickCount() {
		return this.newClickCount;
	}

	public void setNewClickCount(Integer newClickCount) {
		this.newClickCount = newClickCount;
	}

	@Column(name = "new_status", length = 10)
	public String getNewStatus() {
		return this.newStatus;
	}

	public void setNewStatus(String newStatus) {
		this.newStatus = newStatus;
	}

}
