package cn.sz.gl.pojo;

// Generated 2017-3-1 10:46:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Succase generated by hbm2java
 */
@Entity
@Table(name = "succase", catalog = "taiding")
public class Succase implements java.io.Serializable {

	private int caseid;
	private Menu menu;
	private String caseName;
	private String casePicpath;
	private String caseDesc;
	private Date publicTime;
	private String caseStatus;
	private String caseUrl;

	public Succase() {
	}

	public Succase(int caseid, String caseName) {
		this.caseid = caseid;
		this.caseName = caseName;
	}

	public Succase(int caseid, Menu menu, String caseName, String casePicpath,
			String caseDesc, Date publicTime, String caseStatus, String caseUrl) {
		this.caseid = caseid;
		this.menu = menu;
		this.caseName = caseName;
		this.casePicpath = casePicpath;
		this.caseDesc = caseDesc;
		this.publicTime = publicTime;
		this.caseStatus = caseStatus;
		this.caseUrl = caseUrl;
	}

	@Id
	@Column(name = "caseid", unique = true, nullable = false)
	public int getCaseid() {
		return this.caseid;
	}

	public void setCaseid(int caseid) {
		this.caseid = caseid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "case_style")
	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	@Column(name = "case_name", nullable = false, length = 50)
	public String getCaseName() {
		return this.caseName;
	}

	public void setCaseName(String caseName) {
		this.caseName = caseName;
	}

	@Column(name = "case_picpath", length = 100)
	public String getCasePicpath() {
		return this.casePicpath;
	}

	public void setCasePicpath(String casePicpath) {
		this.casePicpath = casePicpath;
	}

	@Column(name = "case_desc")
	public String getCaseDesc() {
		return this.caseDesc;
	}

	public void setCaseDesc(String caseDesc) {
		this.caseDesc = caseDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "public_time", length = 0)
	public Date getPublicTime() {
		return this.publicTime;
	}

	public void setPublicTime(Date publicTime) {
		this.publicTime = publicTime;
	}

	@Column(name = "case_status", length = 10)
	public String getCaseStatus() {
		return this.caseStatus;
	}

	public void setCaseStatus(String caseStatus) {
		this.caseStatus = caseStatus;
	}

	@Column(name = "case_url", length = 100)
	public String getCaseUrl() {
		return this.caseUrl;
	}

	public void setCaseUrl(String caseUrl) {
		this.caseUrl = caseUrl;
	}

}
