package cn.sz.gl.pojo;

// Generated 2017-3-1 10:46:57 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WelcomePic generated by hbm2java
 */
@Entity
@Table(name = "welcome_pic", catalog = "taiding")
public class WelcomePic implements java.io.Serializable {

	private Integer picid;
	private String picpath;
	private String picStatus;

	public WelcomePic() {
	}

	public WelcomePic(String picpath, String picStatus) {
		this.picpath = picpath;
		this.picStatus = picStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "picid", unique = true, nullable = false)
	public Integer getPicid() {
		return this.picid;
	}

	public void setPicid(Integer picid) {
		this.picid = picid;
	}

	@Column(name = "picpath", nullable = false, length = 100)
	public String getPicpath() {
		return this.picpath;
	}

	public void setPicpath(String picpath) {
		this.picpath = picpath;
	}

	@Column(name = "pic_status", nullable = false, length = 10)
	public String getPicStatus() {
		return this.picStatus;
	}

	public void setPicStatus(String picStatus) {
		this.picStatus = picStatus;
	}

}
